### ISSUE TITLE
Array in ctx[:envelope][:to] raise no implicit conversion of Array into String

### ISSUE THREAD

**Issue by factor4** [bb/action-mailbox-docker-relay#1]
Hi! Thank you very much for your service container. It meets exactly my current requirements! :)

I successfully managed to connect it to mailcow and set up a transport for a single mailbox. But when I test it I got "Error: data not accepted".

<img width="711" alt="grafik" src="https://github.com/bb/action-mailbox-docker-relay/assets/783721/30498999-1e41-484d-b94e-204271f6c979">

I set `LOG_LEVEL=DEBUG` in docker compose and look at the output from the container logs. I tracked it down to the following lines:
```
2024-02-17 14:38:25 +0000: [DEBUG] mail received at: [172.22.1.3:2525] from: [<test@factor4.at>] for recipient(s): [["<example@factor4.at>"]]...
```
Here you can see `ctx[:envelope][:to]` comes already as an Array and therefore raise
```
./action_mailbox_relay.rb:22:in `prepend': no implicit conversion of Array into String (TypeError)

      raw_email.prepend("X-Original-To: ", ctx[:envelope][:to], "\n")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from ./action_mailbox_relay.rb:22:in `on_message_data_event'
```
Maybe the solution is to `.join(',')` it if its an Array!? But I'm not sure if this is valid in a mail header?

**Comment by bb** [comment]
Hi Gerald,

thanks for pointing that out. Sorry, `join(',')` won't work. But I found a solution. TLDR: We can add the header multiple times. Fix is committed to main and new image pushed to Docker hub.

Here's the full investigation.

First the incoming part: According to https://github.com/4commerce-technologies-AG/midi-smtp-server/blob/c23736c143c65baea3a8e91636cd37d766bc72dc/lib/midi-smtp-server.rb#L1410 and https://github.com/4commerce-technologies-AG/midi-smtp-server/blob/c23736c143c65baea3a8e91636cd37d766bc72dc/lib/midi-smtp-server.rb#L1262, `[:to]` is _always_ an Array.

Now the outgoing part, i.e. how ActionMailbox actually handles it. In the relay controller which we're using, it's not touched at all.
In the mailgun controller, it supports only one recipient: https://github.com/rails/rails/blob/44db6bbfcbe66ac5926f01f3b693a378552b752f/actionmailbox/app/controllers/action_mailbox/ingresses/mailgun/inbound_emails_controller.rb#L56.
The sendgrid controller actually handles multiple recipients by adding multiple separate headers: https://github.com/rails/rails/blob/44db6bbfcbe66ac5926f01f3b693a378552b752f/actionmailbox/app/controllers/action_mailbox/ingresses/sendgrid/inbound_emails_controller.rb#L61 -- but sendgrid guarantees that the Array has exactly one item: https://docs.sendgrid.com/for-developers/parsing-email/setting-up-the-inbound-parse-webhook#default-parameters

So `ActionMailbox::InboundEmail` just stores the raw source in ActiveStorage and has it parsed like this: `Mail.from_source(source)`.
When passing a source with comma separated value in `X-Original-To`, it shows exactly that in the IRB debug output (line breaks added by me):
```
=> #<Mail::Message:151960, Multipart: false, Headers:
<Date: Mon, 07 Nov 2016 08:45:16 +0000>,
<From: John Smith <john@example.com>>,
<To: Joe Smith <smith@example.com>>,
<Subject: an example.com example email>,
<X-Original-To: test1@example.com,test2@example.net>>
```
but when reading it via the accessor, the second one is gone:
```ruby
pry(main)> mail5.x_original_to_addresses
=> [#<Mail::Address:152860 Address: |test1@example.com| >]
```

However, when prepending the header multiple times, the array has the corresponding number of entries.

I first thought the `from_source` and `x_original_to_addresses` came directly from the Mail gem... but they're actually extensions by ActionMailbox: https://github.com/rails/rails/blob/057563a888fbb3f9237e52b70915edcaf9d797fb/actionmailbox/lib/action_mailbox/mail_ext/addresses.rb#L26.

**Comment by factor4** [comment]
Hi! Thank you so much for fixing it! And for the detailed insight of your research! Now it works as aspected! 👍
